### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by liufeibio** [LKremer/CAFE_fig#4]
Hi, @LKremer 
I am trying to use CAFE_fig to visualize the results from CAFE, but I encountered some problems.
Here is my running: python3 ./CAFE_fig/CAFE_fig.py cafe_result.cafe -c asc=vL, da -pb 0.05 -pf 0.05 --dump test/ -g .pdf --count_all_expansions
And these are output:

Traceback (most recent call last):
  File "./CAFE_fig/CAFE_fig.py", line 517, in <module>
    main(**vars(args))
  File "./CAFE_fig/CAFE_fig.py", line 458, in main
    c = CAFE_fig(report_cafe, families, clades, pb, pf, dump, gfx_output_format, count_all_expansions)
  File "./CAFE_fig/CAFE_fig.py", line 86, in __init__
    self.parse_tree()
  File "./CAFE_fig/CAFE_fig.py", line 136, in parse_tree
    self.parse_lambdas(line)
  File "./CAFE_fig/CAFE_fig.py", line 209, in parse_lambdas
    self.lambda_colors[i] = to_rgb(math.log(lambda_), min_l, max_l)
  File "./CAFE_fig/CAFE_fig.py", line 62, in to_rgb
    v = (v_abs - min_v) / (max_v - min_v)  # scaled to a value between 0 and 1
ZeroDivisionError: float division by zero

Could you help with this? I appreciate your help. Thanks!
Fei

**Comment by LKremer** [comment]
Hi @liufeibio ,
I added a quick fix to the issue, please let me know if it works for you.
Best,
Lukas

**Comment by liufeibio** [comment]
Thanks for your help with this. It solved this problem. But I encountered another problem:
        Writing test/summary.pdf
Traceback (most recent call last):
  File "./CAFE_fig/CAFE_fig.py", line 520, in <module>
    main(**vars(args))
  File "./CAFE_fig/CAFE_fig.py", line 480, in main
    p_value = family.tree.search_nodes(id=node_id)[0].pvalue
AttributeError: 'TreeNode' object has no attribute 'pvalue'
Could you help with this? I appreciate your help. Thanks a lot!

**Comment by Hua-CM** [comment]
> 
> 
> Thanks for your help with this. It solved this problem. But I encountered another problem:
> Writing test/summary.pdf
> Traceback (most recent call last):
> File "./CAFE_fig/CAFE_fig.py", line 520, in
> main(**vars(args))
> File "./CAFE_fig/CAFE_fig.py", line 480, in main
> p_value = family.tree.search_nodes(id=node_id)[0].pvalue
> AttributeError: 'TreeNode' object has no attribute 'pvalue'
> Could you help with this? I appreciate your help. Thanks a lot!

Did you resolve it? I come across the same problem now.

**Comment by liufeibio** [comment]
> > Thanks for your help with this. It solved this problem. But I encountered another problem:
> > Writing test/summary.pdf
> > Traceback (most recent call last):
> > File "./CAFE_fig/CAFE_fig.py", line 520, in
> > main(**vars(args))
> > File "./CAFE_fig/CAFE_fig.py", line 480, in main
> > p_value = family.tree.search_nodes(id=node_id)[0].pvalue
> > AttributeError: 'TreeNode' object has no attribute 'pvalue'
> > Could you help with this? I appreciate your help. Thanks a lot!
> 
> Did you resolve it? I come across the same problem now.

No, I haven't, it is still there.

**Comment by LKremer** [comment]
Hi @liufeibio and @Hua-CM,
sorry for the late reply. I have two questions in order to narrow down the possible causes of the error.
1) Can you reproduce the example plot from the readme file (using example data and the command in the readme)?
2) if so, could you upload your input files here or send them to me via email (L.Kremer _at_ dkfz.de)?
Best, Lukas

**Comment by moveAFs** [comment]
![image](https://user-images.githubusercontent.com/42730275/69946815-4e501380-1527-11ea-8096-f018c4901c84.png)

I guess the problem is the "Lambda:" line (the second line in the cafe out), here is the example from CAFE Manual. As you can see, there is only one lambda value in this line, but your code need more than one values. 

One irrelevant question: how can I get the result with multiple lambda values like your example cafe result?
>Tree:(eda:413,((rpr:357,((((hsa:133,(lhu:132,(cfl:111,(pba:95,(sin:79,(aec:11,ace:11):68):16):16):21):1):29,ame:162):41,nvi:203):122,((dme:272,aae:272):38,tca:310):15):32):1,((((mna:121,cse:121):11,zne:132):96,bge:228):67,lmi:295):63):55)
>Lambda: 0.00110723      0.00261673      0.0116401       0.000535436
>...
