### ISSUE TITLE
AttributeError: 'TreeNode' object has no attribute 'lambda_group'

### ISSUE THREAD

**Issue by wangzhennan14** [LKremer/CAFE_fig#9]
Hi,
CAFE_fig is cool to plot a gene family tree. When I used CAFE_fig to plot my result of cafe (version=4.2.1), there was an error as follow:
Parsing CAFE report... done!
	Writing test/summary.pdf
Traceback (most recent call last):
  File "/CAFE_fig/CAFE_fig.py", line 520, in <module>
    main(**vars(args))
  File "/CAFE_fig/CAFE_fig.py", line 465, in main
    c.summary_tree()
  File "/CAFE_fig/CAFE_fig.py", line 306, in summary_tree
    self.show_or_dump_tree(tree_obj=t, tree_style=ts, fname='summary')
  File "/CAFE_fig/CAFE_fig.py", line 410, in show_or_dump_tree
    tree_obj.render(out_path, tree_style=tree_style)
  File "/Anaconda3/lib/python3.8/site-packages/ete3/coretype/tree.py", line 1392, in render
    return drawer.render_tree(self, file_name, w=w, h=h,
  File "/Anaconda3/lib/python3.8/site-packages/ete3/treeview/drawer.py", line 104, in render_tree
    tree_item, n2i, n2f = render(t, img)
  File "/Anaconda3/lib/python3.8/site-packages/ete3/treeview/qt4_render.py", line 254, in render
    set_style(n, layout_fn)
  File "/Anaconda3/lib/python3.8/site-packages/ete3/treeview/qt4_render.py", line 777, in set_style
    func(n)
  File "/CAFE_fig/CAFE_fig.py", line 270, in fam_size_piechart_layout
    circle_color = self.lambda_colors[node.lambda_group]
AttributeError: 'TreeNode' object has no attribute 'lambda_group'
What is the matter about my result of cafe? Thank you very much!
wang

**Comment by dbellieny** [comment]
Have you managed to work around this one?
I'm getting the same error here.

**Comment by AndrewLeeGla** [comment]
hey, zhennan
I encountered the same problem. Have you figured it out?

**Comment by Dawei-Xia** [comment]
I'm also getted the same error here.

**Comment by chinaxpy** [comment]
I'm also getted the same error here.

**Comment by major-one** [comment]
I had the same problem，i have solved it，There is a problem with a parameter。lambda -s -t (((((((1,1)1,1)1,1)1,1)1,1)1,1)2,2) in cafe.run,-t (((((((1,1)1,1)1,1)1,1)1,1)1,1)2,2) is required !!
